In [1]:
import numpy as np
import pandas as pd

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [2]:
dep_followers_fp = '/home/blackmamba/code/pbragamiranda/dep-followers/data/dep_followers.csv'
dep_followers = pd.read_csv(dep_followers_fp)

dep_info_fp = '/home/blackmamba/code/pbragamiranda/dep-followers/data/dep_description.csv'
dep_info = pd.read_csv(dep_info_fp)

In [3]:
print(dep_followers.columns)
print("---")
print(dep_info.columns)

Index(['id_dep', 'twitter_account', 'date', 'followers'], dtype='object')
---
Index(['id_dep', 'name', 'party', 'UF', 'twitter_account'], dtype='object')

In [4]:
followers = pd.pivot_table(dep_followers, index=['twitter_account'], 
                          columns=['date'], values='followers')

followers.reset_index(level=0, inplace=True)
followers.columns.date = 'id'

In [5]:
followers.head()

date,twitter_account,01/03/2021,02/03/2021,22/02/2021,23/02/2021,24/02/2021,25/02/2021,26/02/2021,27/02/2021,28/02/2021
0,23rubensbueno,14936.0,14937.0,14909.0,14917.0,14920.0,14920.0,14930.0,14934.0,14934.0
1,77_frota,8362.0,8359.0,8215.0,8231.0,8250.0,8261.0,8318.0,8334.0,8354.5
2,AbilioSantana_,7139.0,7138.0,7142.0,7142.0,7144.0,7142.0,7142.0,7143.0,7140.0
3,AcacioFavacho,3774.0,3776.0,3753.0,3754.0,3761.0,3765.0,3764.0,3767.0,3771.0
4,AdolfoViana_,373.0,375.0,349.0,350.0,355.0,355.0,373.0,373.0,373.0

In [6]:
deputies = pd.merge(dep_info, followers, on='twitter_account')

In [7]:
deputies.head()

,id_dep,name,party,UF,twitter_account,01/03/2021,02/03/2021,22/02/2021,23/02/2021,24/02/2021,25/02/2021,26/02/2021,27/02/2021,28/02/2021
0,1,Deputado Abílio Santana,PL,BA,AbilioSantana_,7139.0,7138.0,7142.0,7142.0,7144.0,7142.0,7142.0,7143.0,7140.0
1,2,Deputado Abou Anni,PSL,SP,abou_anni,98.0,99.0,90.0,90.0,90.0,91.0,97.0,97.0,97.0
2,3,Deputado Acácio Favacho,PROS,AP,AcacioFavacho,3774.0,3776.0,3753.0,3754.0,3761.0,3765.0,3764.0,3767.0,3771.0
3,4,Deputado Adolfo Viana,PSDB,BA,AdolfoViana_,373.0,375.0,349.0,350.0,355.0,355.0,373.0,373.0,373.0
4,5,Deputada Adriana Ventura,NOVO,SP,adriventurasp,23037.0,23031.0,22842.0,22855.0,22872.0,22894.0,22989.0,23021.0,23032.0

In [8]:
def diff(x, y):
    return x - y

In [9]:
deputies['diff-28-27'] = diff(deputies['28/02/2021'], deputies['27/02/2021'])
deputies['diff-01-28'] = diff(deputies['01/03/2021'], deputies['28/02/2021'])
deputies['diff-02-01'] = diff(deputies['02/03/2021'], deputies['01/03/2021'])

In [10]:
deputies.sort_values(by='diff-02-01', ascending=True).head(10)

,id_dep,name,party,UF,twitter_account,01/03/2021,02/03/2021,22/02/2021,23/02/2021,24/02/2021,25/02/2021,26/02/2021,27/02/2021,28/02/2021,diff-28-27,diff-01-28,diff-02-01
137,152,Deputado Eduardo Bolsonaro,PSL,SP,BolsonaroSP,1987262.0,1987109.0,1986554.0,1987110.0,1987495.0,1987520.0,1987453.0,1987540.0,1987424.5,-115.5,-162.5,-153.0
293,320,Deputado Luiz Philippe De Orleans E Bragança,PSL,SP,lpbragancabr,589937.0,589865.0,588701.0,588854.0,589061.0,589324.0,589538.0,589683.0,589816.5,133.5,120.5,-72.0
401,442,Deputado Rodrigo Maia,DEM,RJ,RodrigoMaia,952391.0,952330.0,953399.0,953299.0,952818.0,952764.0,952781.0,952836.0,952792.0,-44.0,-401.0,-61.0
422,467,Deputado Silas Câmara,REPUBLICANOS,AM,silascamara_,31545.0,31488.0,31546.0,31547.0,31545.0,31546.0,31552.0,31547.0,31546.0,-1.0,-1.0,-57.0
415,458,Deputado Sargento Fahur,PSD,PR,SargentoFAHUR,618768.0,618713.0,618669.0,618702.0,618765.0,618837.0,618824.0,618807.0,618806.0,-1.0,-38.0,-55.0
295,322,Deputada Major Fabiana,PSL,RJ,majorfabianadep,131527.0,131497.0,NaN,NaN,NaN,NaN,NaN,NaN,131546.5,NaN,-19.5,-30.0
6,7,Deputado Aécio Neves,PSDB,MG,AecioNeves,635486.0,635458.0,635701.0,635674.0,635653.0,635613.0,635572.0,635539.0,635519.0,-20.0,-33.0,-28.0
163,180,Deputado Felipe Francischini,PSL,PR,FFrancischini_,92570.0,92547.0,92629.0,92618.0,92614.0,92595.0,92605.0,92607.0,92589.5,-17.5,-19.5,-23.0
13,15,Deputado Alan Rick,DEM,AC,Alan_Rick,4480.0,4460.0,4455.0,4453.0,4455.0,4457.0,4457.0,4460.0,4460.0,0.0,20.0,-20.0
116,127,Deputado Delegado Éder Mauro,PSD,PA,EderMauroPA,78500.0,78484.0,78400.0,78415.0,78438.0,78465.0,78476.0,78491.0,78504.5,13.5,-4.5,-16.0

In [11]:
deputies[deputies['diff-02-03'].notnull()].sort_values(by='diff-02-03', ascending=True).tail(10)

KeyError: 'diff-02-03'

In [13]:
deputies.groupby(['party'])['28/02/2021'].sum().reset_index().sort_values(by='28/02/2021', ascending=False)

            party  28/02/2021
16            PSL   8012602.0
17           PSOL   3505757.0
18             PT   3353956.0
2             DEM   1826831.0
22   REPUBLICANOS    959909.0
14            PSD    913706.5
15           PSDB    879618.0
7             PDT    678715.0
4            NOVO    656021.0
13            PSC    596834.0
12            PSB    570866.5
10             PP    560507.5
6           PCdoB    555397.5
3             MDB    462816.5
8              PL    192637.5
9            PODE    150892.5
1       CIDADANIA    129527.5
0          AVANTE    129302.5
11           PROS    129282.5
23  SOLIDARIEDADE     46339.0
19            PTB     24840.0
5        PATRIOTA     15047.5
20             PV     14210.0
21           REDE     10225.0

In [74]:
deputies.groupby(['UF'])['28/02/2021'].sum().reset_index().sort_values(by='28/02/2021', ascending=False)

    UF  28/02/2021
25  SP   8270529.5
18  RJ   5796088.0
17  PR   2565633.5
22  RS   2052634.0
10  MG   1489081.5
6   DF   1025349.0
23  SC    493014.5
4   BA    412611.5
15  PE    319048.0
8   GO    294748.0
7   ES    265710.0
19  RN    244064.5
1   AL    166583.5
5   CE    163282.0
12  MT    137929.0
13  PA    130594.0
14  PB    107858.5
2   AM     86984.5
21  RR     77295.0
3   AP     65215.5
9   MA     46085.5
24  SE     41580.0
11  MS     32896.0
16  PI     26345.0
0   AC     26179.5
26  TO     24567.0
20  RO     13934.5